spring:
  application:
    name: geoapp
  data:
    mongodb:
      host: localhost
      port: 27017
      database: geoappdb
      auto-index-creation: true
  redis:
    host: localhost
    port: 6379
server:
  port: 8081

system-info:
  api:
    url: "https://api.restful-api.dev/objects"

weather:
  api:
    url: "http://api.weatherapi.com/v1/current.json?key=API_KEY&q=CITY&aqi=yes"
    key: "***************************"